<!-- content container on the right -->
<div id="content_container" class="col-md-10 col-md-offset-1">                	
    <div id="content_title">
		Contact Us
	</div>
    <div id="content_body" class="col-md-8 col-md-offset-2">
		<div id="contact_form">
			<form role="form">
			  <div class="form-group">
				<label for="exampleInputEmail1">Email address</label>
				<input type="email" class="form-control" id="exampleInputEmail1" placeholder="Enter email">
			  </div>
			  <div class="form-group">
				<label for="exampleInputPassword1">Password</label>
				<input type="password" class="form-control" id="exampleInputPassword1" placeholder="Password">
			  </div>
			  <div class="form-group">
				<label for="exampleInputFile">Message</label>
				<textarea class="form-control" rows="4"></textarea>
			  </div>							  
			  <button type="submit" class="btn btn-default">Submit</button>
			</form>
		</div>
		
	</div>
</div>