<!-- holds the home page banner -->
   <div id="main_banner" class="jumbotron">
        <h1>Some introductory statement</h1>
        <h3>something more interesting</h3>
        <!-- login and sign up buttons  -->
        <div id="home_buttons" class="col-md-5 col-md-offset-5">
            <button id="login_button" class="btn btn-primary">Log in</button>
            <button id="sign-up_button" class="btn btn-success">Sign up</button>
         </div>
    </div>
    <!-- some of the services offered -->
    <div id="services_section">
    	<div class="container">
        	<div class="row">
            	<!-- service 1 -->
                <div id="service" class="col-md-4">
                    <h4 id="service_header">Study</h4>
                    <p>
						Get access to guidance and opportunities to help you achieve your dream career.<br>
						<a href="<?php echo $this->urlStudy; ?>">learn more</a>
					</p>
                </div>
                <!-- service 2 -->
                <div id="service" class="col-md-4">
                    <h4 id="service_header">Internship and Training</h4>
                    <p>
						Opportunities for you to gain experience and get access to new skills.<br>
						<a href="<?php echo $this->urlJobs; ?>">learn more</a>
					</p>
                </div>
                <!-- service 3 -->
                <div id="service" class="col-md-4">
                    <h4 id="service_header">Research</h4>
                    <p>
						Create awareness and opportunities for you to come up with innovative solutions to current challenges; 
						bridging the gap between theory and practical.
						<a href="<?php echo $this->urlResearch; ?>">learn more</a>
					</p>
                </div>
            </div>
        </div>
    </div>
    <!-- end of services offered -->