<div id="content_container" class="col-md-10 col-md-offset-1">                	
    <div id="content_title">
		Study
	</div>
	<div id="content_body">
		<p>
			Are you unclear of where you want to study? Do you have big educational dreams but limited resources to archive them?  
			Are you looking for guidance on educational path?
		</p>
		<p>
			We at Maranatha Services provide information about worldwide scholarships, 
			give advices and provide services to gaining admission to study abroad. 
			All you need to do is to make your requirement known and we will provide suitable solutions.
		</p>
		<p>
			On our website, you can find scholarships information, information on institutes, majors (specialties), cost, countries etc. 
			that could help you in making the right decision for your future.
		</p>
	</div>
</div>
                