<div id="footer_navigation" class="text-center">
<!-- holder for the content navigation in the footer -->
<ul class="list-inline">
	<li><a href="<?php echo $this->urlPrivacyPolicy; ?>">Privacy Policy</a></li>
	<li><a href="<?php echo $this->urlTerms; ?>">Terms</a></li>
	<li><a href="<?php echo $this->urlAbout; ?>">About</a></li>
</ul>
</div>
<div id="copyright" class="text-center">
	<!-- holder for the copyright information in the footer -->
	
</div>				