<!-- logo section -->
<div id="logo" class="nav navbar-brand">
	<a href="<?php echo $this->urlHome; ?>">logo</a>
</div>

<!-- header menu -->
<div id="header_menu" class="col-md-2 col-md-offset-9">
	<ul class="nav navbar-nav">
    	<li><a href="<?php echo $this->urlAbout; ?>" >About</a></li>
        <li><a href="<?php echo $this->urlContacts; ?>">Contact</a></li>
     </ul>                       
</div>
<!-- end header menu -->