<!-- content container on the right -->
<div id="content_container" class="col-md-10 col-md-offset-1">                	
    <div id="content_title">
		About
	</div>
    <div id="content_body">
		<p>
			Maranatha Service is an educational company dedicated to filling the gap of education institutes and prepares individuals for future challenges.
		</p>
		<p>
			Education: We make opportunity visible for individuals who are planning on further education either by scholarship, self-sponsoring, locally or internationally; 
			providing services according to everyone’s capacity.
		</p>
		<p>
			Research: We facilitate research issued by Maranatha Services, organizations or proposed by Individuals; 
			providing solution to the future challenges.
		</p>
		<p>
			Jobs/Internships: We host opportunities for internship and jobs, giving individuals opportunity to suitable positions and 
			organization to find the suitable candidates for such career opportunities.
		</p>
	</div>
</div>