<div id="content_container" class="col-md-10 col-md-offset-1">                	
    <div id="content_title">
		Jobs and Internship
	</div>
    <div id="content_body">
		<p>
			We host internship and job vacancies for organizations to help individuals find opportunities easily worldwide.
		</p>
		<p>
			Organizations with registered accounts can easily find suitable candidates through our search engine for various projects all around the world.
		</p>
	</div>
	<div id="content_title">
		Training and Certifications
	</div>
	<div id="content_body">
		<p>
			Registered organization post certification training information and 
			individuals could register for such training after which the completion of such training will offer certificates for participant.
		</p>
	</div>
</div>