<div id="content_container" class="col-md-10 col-md-offset-1">                	
    <div id="content_title">
		Research
	</div>
	<div id="content_body">
		<p>
			Organization: We provide innovative solutions to organizations that need results on some research topics. 
			All you need to do is to provide the topic and guaranteed reward. Maranatha Service coordinate individuals from all over the world with a combine knowledge in providing solutions as requested.
		</p>
		<p>
			Individuals: You can propose beneficial research topics. 
			After a successful evaluation, we will invite application of individuals from various part of the world to participate in the research.
		</p>
		<p>
			Maranatha Services: We also publish research and invites Individual to participate.
		</p>
		</p>
			Part of the benefit of such research is gaining professional experience, 
			certification awarded by Maranatha Services and contributing to world development.
		</p>
	</div>
</div>